version: '3.8'

services:
  todolist-api:
    build: .
    container_name: todolist-api-container
    environment:
      - MYSQL_HOST=db
    ports:
      - "8080:8080"
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - db
    volumes:
      - ./src:/app/src  # Optional: Mount local source code for live updates (if needed)

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Fetch from .env file
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Fetch from .env file
      MYSQL_USER: ${MYSQL_USER}  # Fetch from .env file
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:   